# Neural Network

### Import Libraries

In [31]:
import numpy as np
import tensorflow as tf
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.regularizers import l2
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler, LabelEncoder
from tensorflow.keras.utils import to_categorical
from sklearn.feature_extraction.text import CountVectorizer


### Load dataset

In [3]:
# Load dataset
data = pd.read_csv('C://Users//Jayashrinidhi V//OneDrive//Documents//VScode//AlgoMaster//data_700_5.csv')
print(data.head())

  algorithm                                          plaintext  \
0       AES  :L0@86._C.,y@}tkOz"Pfjrd.:_~<V##~;X!)&2p]lfng2...   
1       AES                               qn3=6B)oqGX585a_[4IU   
2       AES  In the world of human rights, data integrity p...   
3       AES  0/xe+$jEcc:Lgm<mu&yz, Q|Q@QdjH ?eUx&_Z_xw._-%p...   
4       AES  2Kdg~|%lLG~b{7ggU^Y<D|HcQ'w0dyQF7[1HQU%4F/D`@4...   

                                                 key  \
0  b6928ad6150f1fdb90ceca40c3b41c0e256a2108852a2a...   
1  58961e57dd0706c30a78f4db788a3ca374361f57e50362...   
2  9b894ca23e60cfddacda7fbff2448ac183377f0e52bd36...   
3  5b3bad22934a6e6b4568d4455fe521941fa886a1df36f9...   
4  4dd9fc66a4e54d43597291ceff00ed73ab56356b2d13d1...   

                                 iv  \
0  fcadfe9253f711ea3e0d42fe96e7be09   
1  696dfe1c1abb2374f3739af173a825de   
2  3b074c00bb75cb36bd0c13f167452630   
3  c767572137d5a8e56d6ff12ee1ddfe58   
4  b96a2a1503677b500d278d54e2bab111   

                               

In [4]:
# Check for missing values
print(data.isnull().sum())

algorithm            0
plaintext            0
key                  0
iv                   0
encrypted_message    0
dtype: int64


In [5]:
# Encode the target variable
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(data['algorithm'])


# Vectorize the text data
vectorizer = CountVectorizer(analyzer='char', ngram_range=(1, 2))  # Character-level 1-2 gram analysis
plaintext_features = vectorizer.fit_transform(data['plaintext'])
key_features = vectorizer.transform(data['key'])
iv_features = vectorizer.transform(data['iv'])
encrypted_message_features = vectorizer.transform(data['encrypted_message'])

# Convert sparse matrices to dense arrays
plaintext_features = plaintext_features.toarray()
key_features = key_features.toarray()
iv_features = iv_features.toarray()
encrypted_message_features = encrypted_message_features.toarray()


In [7]:
# Concatenate all features
X = np.hstack([
    plaintext_features,
    key_features,
    iv_features,
    encrypted_message_features
])


In [8]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


In [9]:
# Prepare the target variable for multi-class classification
y_encoded = to_categorical(y_encoded)

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_encoded, test_size=0.2, random_state=42)


In [10]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Create the neural network model
model = Sequential()
#model.add(Dense(units=32, activation='relu', input_dim=X_train.shape[1]))
#model.add(Dense(units=16, activation='relu'))

model.add(Dense(units=16, activation='relu', input_dim=X_train.shape[1]))

model.add(Dense(units=y_train.shape[1], activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


c:\Users\Jayashrinidhi V\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [104]:
"""from tensorflow.keras.optimizers import Adam

# Define the learning rate
learning_rate = 0.0001

# Create the neural network model
model = Sequential()
model.add(Dense(units=64, activation='relu', input_dim=X_train.shape[1]))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=y_train.shape[1], activation='softmax'))

# Compile the model with the learning rate
optimizer = Adam(learning_rate=learning_rate)
model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])
"""

from tensorflow.keras.optimizers import Adam

# Define the learning rate
learning_rate = 0.001

# Create the neural network model
model = Sequential()
model.add(Dense(units=16, activation='softmax', input_dim=X_train.shape[1]))
#model.add(Dense(units=16, activation='relu'))
model.add(Dense(units=y_train.shape[1], activation='softmax'))

# Compile the model with the learning rate
optimizer = Adam(learning_rate=learning_rate)
model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])


c:\Users\Jayashrinidhi V\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [105]:
# Train the model
#history = model.fit(X_train, y_train, epochs=30, batch_size=8, validation_split=0.2, verbose=1)
"""#
 for 60
from tensorflow.keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)
history = model.fit(X_train, y_train, epochs=10,batch_size=64, validation_split=0.2, callbacks=[early_stopping])

"""

from tensorflow.keras.callbacks import EarlyStopping

early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)
history = model.fit(X_train, y_train, epochs=20,batch_size=32, validation_split=0.2, callbacks=[early_stopping])


Epoch 1/20
70/70 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.2250 - loss: 1.5892 - val_accuracy: 0.5000 - val_loss: 1.4795
Epoch 2/20
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6962 - loss: 1.3419 - val_accuracy: 0.5679 - val_loss: 1.3779
Epoch 3/20
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8083 - loss: 1.1891 - val_accuracy: 0.5875 - val_loss: 1.3168
Epoch 4/20
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8654 - loss: 1.0753 - val_accuracy: 0.6179 - val_loss: 1.2742
Epoch 5/20
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8865 - loss: 0.9791 - val_accuracy: 0.6214 - val_loss: 1.2250
Epoch 6/20
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8988 - loss: 0.9021 - val_accuracy: 0.6214 - val_loss: 1.1802
Epoch 7/20
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9136 - loss: 0.8238 - val_accuracy: 0.6393 - val_loss: 1.1354
Epoch 8/20
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9255 - loss: 0.7655 - val_accuracy: 0.6607 - val_loss:

In [107]:
# Save the trained model to a file
model.save('neural_network_model.h5')
print("Model saved to 'neural_network_model.h5'")


Model saved to 'neural_network_model.h5'


In [106]:

# Evaluate the model
test_loss, test_accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"Test Accuracy: {test_accuracy:.4f}")

# Predict on the test set
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test, axis=1)

# Print classification report and confusion matrix
from sklearn.metrics import classification_report, confusion_matrix
print("Classification Report:")
print(classification_report(y_true, y_pred_classes))
print("Confusion Matrix:")
print(confusion_matrix(y_true, y_pred_classes))


Test Accuracy: 0.6571
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
Classification Report:
              precision    recall  f1-score   support

           0       0.43      0.25      0.32       138
           1       0.96      0.84      0.89       167
           2       0.88      0.88      0.88       120
           3       0.76      0.77      0.76       137
           4       0.35      0.54      0.43       138

    accuracy                           0.66       700
   macro avg       0.67      0.66      0.66       700
weighted avg       0.68      0.66      0.66       700

Confusion Matrix:
[[ 35   0   5  14  84]
 [  0 140   0  10  17]
 [  2   0 105   0  13]
 [  6   2   0 105  24]
 [ 39   4  10  10  75]]
